version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
  db:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clients
